### ISSUE TITLE
Code of Conduct?

### ISSUE THREAD

**Issue by berbiche** [notarock/traduirbot#4]
See title

**Comment by notarock** [comment]
![image](https://user-images.githubusercontent.com/25652765/118384200-3280e600-b5d2-11eb-8e50-09ac523f6aeb.png)

**Comment by AXDOOMER** [comment]
Proposal for article one of the CoC:

1- Indent the Python code with tabs or else it's antisemitism.

**Comment by notarock** [comment]
`!remindme 2 years`
